"""Updated tables

Revision ID: 1f676e3fe1d7
Revises: 81076cd7a620
Create Date: 2024-12-21 10:12:26.378298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f676e3fe1d7'
down_revision = '81076cd7a620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.drop_column('comment')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)

    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
