"""added photo to event model

Revision ID: 1ff96d5fea56
Revises: 8ed0ed27b787
Create Date: 2025-01-08 13:53:00.392154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff96d5fea56'
down_revision = '8ed0ed27b787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_hero', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('event_hero')

    # ### end Alembic commands ###
